### PR TITLE
Fix for navigation buttons that don't update on certain websites.

### PR DESCRIPTION
**Pull request by codyfish**
I've noticed that on social media websites that seem not to load a new page when changing content (e.g. reddit and instagram) no `load-changed` event is fired by the webkitgkt2 webview even though it can go back. Therefore the sensitivity of the reload buttons doesn't update.

I added a very ugly fix as I  haven't found any event for page changes: I listen on 'resource-load-started'. This sadly spams checks on `canGoBack()` and `canGoForward` when loading a new page. Furthermore, it also doesn't use any variable passed to it but without them in the lambda definition the pages somehow sometimes work and sometimes don't, therefore I had to push ignoring push-hooks.

I hope to find a cleaner solution on this.

It works though.

I didn't know if I should open an issue first, so I thought I'd just create a pull request for my quick-fix.

### CODE REVIEW

**Comment by sonnyp** [comment]
@codyfish thanks.

I also experienced the issue and was looking forward a fix but I think I merged this too fast.
After merging this I looked into how Epiphany does it and it is actually quite straightforward (but not trivial to found).

https://gjs-docs.gnome.org/webkit240~4.0_api/webkit2.webview#method-get_back_forward_list
When you get that object you can listen to the `change` signal.

Looks like it would allow to remove this hack and the current way.

Reference: https://gitlab.gnome.org/GNOME/epiphany/blob/master/embed/ephy-web-view.c#L1188 

Would you like to work on this?

**Comment by sonnyp** [comment]
Something like 

```js
function updateButtons() {
    backButton.sensitive = webview.can_go_back();
    forwardButton.sensitive = webview.can_go_forward();
}
// call updateButtons when switching tabs

const backForwardList = webview.get_back_forward_list();
// disconnect when switching tab
backForwardList.connect('change', updateButton);
```

**Comment by codyfish** [comment]
Yeah, I'll look into it tomorrow!

**Comment by sonnyp** [comment]
cool!

Related issue that should be straightforward to fix at the same time, when you switch tab, Tangram does not update the sensitivity of the buttons. I think calling `updateButtons` in `webview` state change should be enough.

**Pull request merged**
